### ISSUE TITLE
Create mappings to MITRE ATT&CK Framework

### ISSUE THREAD

**Issue by dpramone** [Cloud-Architekt/AzureAD-Attack-Defense#17]
It would be massively cool to have a full mapping of both attacks and defenses to the MITRE ATT&CK Framework as to have a translation into a common language for easy integration into existing ATT&CK-based defense solutions.

**Comment by Cloud-Architekt** [comment]
Thanks for your feedback and idea! @samilamppu and I've worked on MITRE ATT&CK mapping ... the result can be found in the latest update of the playbook. Enjoy! :) We're always happy to hear your feedback...

**Comment by dpramone** [comment]
> Thanks for your feedback and idea! @samilamppu and I've worked on MITRE ATT&CK mapping ... the result can be found in the latest update of the playbook. Enjoy! :) We're always happy to hear your feedback...

Absolutely smashing addition, guys. Thank you so much.
