### ISSUE TITLE
managed identity not created

### ISSUE THREAD

**Issue by DeanGross** [Cloud-Architekt/AzureAD-Attack-Defense#33]
After deploying to Azure, I don't see the Managed Identity "Import-AADSCAtoLAWS" that is described in the documentation. It is not listed in the resource group, nor is it listed int he Managed Identities portal I did not see any errors during the deployment. 

I do see a Logic App named "Import-AADSCAtoLAWS", it appears that the documentation may be incorrect, and that the "Managed Identity" named "Import-AADSCAtoLAWS", should actually be a logic app.

**Comment by Cloud-Architekt** [comment]
Hi @DeanGross, thanks for you feedback! Good catch... We have improved the description of the managed identity.
There was a wrong description about different names in the docs before.

The managed identity should be visible in the [Enterprise App Blade of Azure AD](https://portal.azure.com/#view/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/~/AppAppsPreview/menuId~/null) with the same name as the logic app. It's a system-assigned managed identity which will be enabled as part of the ARM deployment. You can check the status also in the "Identity" blade of the Logic App. I've double checked the deployment in my lab, it works as expected.

Please give me a short feedback if this works for you.

CC: @samilamppu, @mpitkaranta

**Comment by DeanGross** [comment]
@Cloud-Architekt , that worked for me. I did have to run the logic app twice because the identity did not yet have the necessary permissions. but after waiting a few more minutes it worked. 
When do you think that you will be able to add the "Coming soon" analyses?

**Comment by Cloud-Architekt** [comment]
I hope we will find some spare time to publish them within the next few months...
